
[brick]
name = "CdoExtras"
version = "0.1.0"
chplVersion = "1.17.0"
authors = ["Brian Dolan: buddha314@gmail.com"]
source = "https://github.com/buddha314/cdo-extras"

[dependencies]
Cdo = '0.1.1'
NumSuch = '0.2.2'
